/*
 * xgameruntime.dll implementation
 *
 * Written by Weather
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep header

import "propidl.idl";
import "xasync.idl";
import "xasyncprovider.idl";
import "xgameruntimefeature.idl";
import "xsystem.idl";
import "xtaskqueue.idl";
import "xuser.idl";

/* --- xgameruntime --- */

interface IWineAsyncWork;
interface IXGameRuntimeFeature;
interface IXSystem;
interface IXSystemAnalytics;
interface IXThreading;
interface IXUser;
interface IXUser2;
interface IXUser3;
interface IXUser4;
interface IXUser5;
interface IXUser6;
interface IXUserGamertag;
interface IXUserDevice;

coclass XGameRuntimeFeatureImpl;
coclass XSystemImpl;
coclass XSystemAnalyticsImpl;
coclass XThreadingImpl;
coclass XUserImpl;
coclass XUserDeviceImpl;

[ local, object, uuid(7664288b-54e9-45f9-af0b-b4ad047fa194) ]
interface IWineAsyncWorkImpl : IUnknown
{}

[ local, object, uuid(8836fe87-edb9-4fe3-8dad-05f0d2cd5b40) ]
interface IXGameRuntimeFeature : IUnknown
{
    BOOLEAN XGameRuntimeIsFeatureAvailable( [in] XGameRuntimeFeature feature );
}

[ local, object, uuid(dadc2895-34b0-4ef5-a83e-45114d629b80) ]
interface IXSystem : IUnknown
{
    HRESULT XSystemGetConsoleId( [in] INT32 consoleIdSize, [out, size_is(consoleIdSize)] CHAR *consoleId, [out, optional] SIZE_T *consoleIdUsed );
    HRESULT XSystemGetXboxLiveSandboxId( [in] INT32 sandboxIdSize, [out, size_is(sandboxIdSize)] CHAR *sandboxId, [out] SIZE_T *sandboxIdUsed );
    HRESULT XSystemGetAppSpecificDeviceId( [in] INT32 appSpecificDeviceIdSize, [out, size_is(appSpecificDeviceIdSize)] CHAR *appSpecificDeviceId, [out, optional] SIZE_T *appSpecificDeviceIdUsed );
    HRESULT XSystemHandleTrack( [in] XSystemHandleCallback callback, [in, optional] void *context );
    BOOLEAN XSystemIsHandleValid( [in] XSystemHandle handle );
    HRESULT XSystemAllowFullDownloadBandwidth( [in] BOOLEAN enable );
}

[ local, object, uuid(b884675d-b738-4a9c-815d-9a9a1e0c6c9b) ]
interface IXSystemAnalytics : IUnknown
{
    XSystemAnalyticsInfo XSystemGetAnalyticsInfo();
}

[ local, object, uuid(073b7dcb-1fcf-4030-94be-e3c9eb623428) ]
interface IXThreading : IUnknown
{
    HRESULT XAsyncGetStatus( [in, out] XAsyncBlock *asyncBlock, [in] BOOLEAN wait );
    HRESULT XAsyncGetResultSize( [in, out] XAsyncBlock *asyncBlock, [out] SIZE_T *bufferSize );
    void    XAsyncCancel( [in, out] XAsyncBlock *asyncBlock );
    HRESULT XAsyncRun( [in, out] XAsyncBlock *asyncBlock, [in] XAsyncWork *work );
    HRESULT XAsyncBegin( [in, out] XAsyncBlock *asyncBlock, [in, optional] void *context, [in, optional] const void *identity, [in, optional] const CHAR *identityName, [in] XAsyncProvider *provider );
    HRESULT __PADDING__();
    HRESULT XAsyncSchedule( [in, out] XAsyncBlock *asyncBlock, [in] UINT32 delayInMs );
    void    XAsyncComplete( [in, out] XAsyncBlock *asyncBlock, [in] HRESULT result, [in] SIZE_T requiredBufferSize );
    HRESULT XAsyncGetResult( [in, out] XAsyncBlock *asyncBlock, [in, optional] const void *identity, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XTaskQueueCreate( [in] XTaskQueueDispatchMode workDispatchMode, [in] XTaskQueueDispatchMode completionDispatchMode, [out] XTaskQueueHandle *queue );
    HRESULT XTaskQueueCreateComposite( [in] XTaskQueuePortHandle workPort, [in] XTaskQueuePortHandle completionPort, [out] XTaskQueueHandle *queue );
    HRESULT XTaskQueueGetPort( [in] XTaskQueueHandle queue, [in] XTaskQueuePort port, [out] XTaskQueuePortHandle *portHandle );
    HRESULT XTaskQueueDuplicateHandle( [in] XTaskQueueHandle queueHandle, [out] XTaskQueueHandle *duplicatedHandle );
    BOOLEAN XTaskQueueDispatch( [in] XTaskQueueHandle queue, [in] XTaskQueuePort port, [in] UINT32 timeoutInMs );
    void    XTaskQueueCloseHandle( [in] XTaskQueueHandle queue );
    HRESULT XTaskQueueSubmitCallback( [in] XTaskQueueHandle queue, [in] XTaskQueuePort port, [in, optional] void *callbackContext, [in] XTaskQueueCallback *callback );
    HRESULT XTaskQueueSubmitDelayedCallback( [in] XTaskQueueHandle queue, [in] XTaskQueuePort port, [in] UINT32 delayMs, [in, optional] void *callbackContext, [in] XTaskQueueCallback *callback );
    HRESULT XTaskQueueRegisterWaiter( [in] XTaskQueueHandle queue, [in] XTaskQueuePort port, [in] HANDLE waitHandle, void *callbackContext, XTaskQueueCallback *callback, XTaskQueueRegistrationToken *token );
    void    XTaskQueueUnregisterWaiter( [in] XTaskQueueHandle queue, [in] XTaskQueueRegistrationToken token );
    HRESULT XTaskQueueTerminate( [in] XTaskQueueHandle queue, [in] BOOLEAN wait, [in, optional] void *callbackContext, [in, optional] XTaskQueueTerminatedCallback *callback );
    HRESULT XTaskQueueRegisterMonitor( [in] XTaskQueueHandle queue, [in, optional] void *callbackContext, [in] XTaskQueueMonitorCallback *callback, [out] XTaskQueueRegistrationToken *token );
    void    XTaskQueueUnregisterMonitor( [in] XTaskQueueHandle queue, [in] XTaskQueueRegistrationToken token );
    BOOLEAN XTaskQueueGetCurrentProcessTaskQueue( [out] XTaskQueueHandle *queue );
    void    XTaskQueueSetCurrentProcessTaskQueue( [in] XTaskQueueHandle queue );
    HRESULT XThreadSetTimeSensitive( [in] BOOLEAN isTimeSensitiveThread );
    HRESULT __PADDING_2__();
    void    XThreadAssertNotTimeSensitive();
    BOOLEAN XThreadIsTimeSensitive();
}

[ local, object, uuid(01acd177-91f9-4763-a38e-ccbb55ce32e0) ]
interface IXUser : IUnknown
{
    HRESULT XUserDuplicateHandle( [in] XUserHandle handle, [out] XUserHandle *duplicatedHandle );
    void    XUserCloseHandle( [in] XUserHandle user );
    INT32   XUserCompare( [in, optional] XUserHandle user1, [in, optional] XUserHandle user2 );
    HRESULT XUserGetMaxUsers( [out] UINT32 *maxUsers );
    HRESULT XUserAddAsync( [in] XUserAddOptions options, [in, out] XAsyncBlock *async );
    HRESULT XUserAddResult( [in, out] XAsyncBlock *async, [out] XUserHandle *newUser );
    HRESULT XUserGetLocalId( [in] XUserHandle user, [out] XUserLocalId *userLocalId );
    HRESULT XUserFindUserByLocalId( [in] XUserLocalId userLocalId, [out] XUserHandle *handle );
    HRESULT XUserGetId( [in] XUserHandle user, [out] UINT64 *userId );
    HRESULT XUserFindUserById( [in] UINT64 userId, [out] XUserHandle *handle );
    HRESULT XUserGetIsGuest( [in] XUserHandle user, [out] boolean *isGuest );
    HRESULT XUserGetState( [in] XUserHandle user, [out] XUserState *state );
    HRESULT __PADDING__();
    HRESULT XUserGetGamerPictureAsync( [in] XUserHandle user, [in] XUserGamerPictureSize pictureSize, [in, out] XAsyncBlock *async );
    HRESULT XUserGetGamerPictureResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *bufferSize );
    HRESULT XUserGetGamerPictureResult( [in, out] XAsyncBlock *async, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XUserGetAgeGroup( [in] XUserHandle user, [out] XUserAgeGroup *ageGroup );
    HRESULT XUserCheckPrivilege( [in] XUserHandle user, [in] XUserPrivilegeOptions options, [in] XUserPrivilege privilege, [out] boolean *hasPrivilege, [out, optional] XUserPrivilegeDenyReason *reason );
    HRESULT XUserResolvePrivilegeWithUiAsync( [in] XUserHandle user, [in] XUserPrivilegeOptions options, [in] XUserPrivilege privilege, [in, out] XAsyncBlock *async );
    HRESULT XUserResolvePrivilegeWithUiResult( [in, out] XAsyncBlock *async );
    HRESULT XUserGetTokenAndSignatureAsync( [in] XUserHandle user, [in] XUserGetTokenAndSignatureOptions options, [in, string] const CHAR *method, [in, string] const CHAR *url, [in] SIZE_T headerCount, [in, optional, length_is(headerCount)] const XUserGetTokenAndSignatureHttpHeader headers[*], [in] SIZE_T bodySize, [in, optional, size_is(bodySize)] const void *bodyBuffer, [in, out] XAsyncBlock *async );
    HRESULT XUserGetTokenAndSignatureResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *bufferSize );
    HRESULT XUserGetTokenAndSignatureResult( [in, out] XAsyncBlock *async, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out] XUserGetTokenAndSignatureData **ptrToBuffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XUserGetTokenAndSignatureUtf16Async( [in] XUserHandle user, [in] XUserGetTokenAndSignatureOptions options, [in, string] const WCHAR *method, [in, string] const WCHAR *url, [in] SIZE_T headerCount, [in, optional, length_is(headerCount)] const XUserGetTokenAndSignatureUtf16HttpHeader headers[*], [in] SIZE_T bodySize, [in, optional, size_is(bodySize)] const void *bodyBuffer, [in, out] XAsyncBlock *async );
    HRESULT XUserGetTokenAndSignatureUtf16ResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *bufferSize );
    HRESULT XUserGetTokenAndSignatureUtf16Result( [in, out] XAsyncBlock *async, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out] XUserGetTokenAndSignatureUtf16Data **ptrToBuffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XUserResolveIssueWithUiAsync( [in] XUserHandle user, [in, optional, string] const CHAR *url, [in, out] XAsyncBlock *async );
    HRESULT XUserResolveIssueWithUiResult( [in, out] XAsyncBlock *async );
    HRESULT XUserResolveIssueWithUiUtf16Async( [in] XUserHandle user, [in, optional, string] const WCHAR *url, [in, out] XAsyncBlock *async );
    HRESULT XUserResolveIssueWithUiUtf16Result( [in, out] XAsyncBlock *async );
    HRESULT XUserRegisterForChangeEvent( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XUserChangeEventCallback *callback, [out] XTaskQueueRegistrationToken *token );
    boolean XUserUnregisterForChangeEvent( [in] XTaskQueueRegistrationToken token, [in] boolean wait );
    HRESULT XUserGetSignOutDeferral( [out] XUserSignOutDeferralHandle *deferral );
    void    XUserCloseSignOutDeferralHandle( [in] XUserSignOutDeferralHandle deferral );
}

[ local, object, uuid(eb9bf948-18dc-4d82-bbcc-40e0a809c4c0) ]
interface IXUser2 : IXUser
{
    HRESULT XUserAddByIdWithUiAsync( [in] UINT64 userId, [in, out] XAsyncBlock *async );
    HRESULT XUserAddByIdWithUiResult( [in, out] XAsyncBlock *async, [out] XUserHandle *newUser );
}

[ local, object, uuid(1bf2f8c5-d507-4e52-bb05-f726d0e71161) ]
interface IXUser3 : IXUser2
{
    HRESULT XUserGetMsaTokenSilentlyAsync( [in] XUserHandle user, [in] XUserGetMsaTokenSilentlyOptions options, [in, string] const CHAR *scope, [in, out] XAsyncBlock *async );
    HRESULT XUserGetMsaTokenSilentlyResult( [in, out] XAsyncBlock *async, [in] SIZE_T resultTokenSize, [out, string, size_is(resultTokenSize)] CHAR *resultToken, [out, optional] SIZE_T *resultTokenUsed );
    HRESULT XUserGetMsaTokenSilentlyResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *tokenSize );
}

[ local, object, uuid(079415e3-6727-437f-8e9d-8f8f9b2439f7) ]
interface IXUser4 : IXUser3
{
    boolean XUserIsStoreUser( [in] XUserHandle user );
}

[ local, object, uuid(26f3c674-a2fe-44fa-b6c4-a323bc94ff53) ]
interface IXUser5 : IXUser4
{
    HRESULT XUserPlatformRemoteConnectSetEventHandlers( [in, optional] XTaskQueueHandle queue, [in] XUserPlatformRemoteConnectEventHandlers *handlers );
    HRESULT XUserPlatformRemoteConnectCancelPrompt( [in] XUserPlatformOperation operation );
    HRESULT XUserPlatformSpopPromptSetEventHandlers( [in, optional] XTaskQueueHandle queue, [in] XUserPlatformSpopPromptEventHandler *handler, [in, optional] void *context );
    HRESULT XUserPlatformSpopPromptComplete( [in] XUserPlatformOperation operation, [in] XUserPlatformOperationResult result );
}

[ local, object, uuid(5131d685-4394-4ee6-8c18-bfb5d4aef1ff) ]
interface IXUser6 : IXUser5
{
    boolean XUserIsSignOutPresent();
    HRESULT XUserSignOutAsync( [in] XUserHandle user, [in, out] XAsyncBlock *async );
    HRESULT XUserSignOutResult( [in, out] XAsyncBlock *async );
}

[ local, object, uuid(cef4fac0-7676-4a94-a119-4c43f9eb5b74) ]
interface IXUserGamertag : IUnknown
{
    HRESULT XUserGetGamertag( [in] XUserHandle user, [in] XUserGamertagComponent gamertagComponent, [in] SIZE_T gamertagSize, [out, string, size_is(gamertagSize)] CHAR *gamertag, [out, optional] SIZE_T *gamertagUsed );
}

[ local, object, uuid(0cc6a956-e7e1-4fdf-9341-9d5da649ebc8) ]
interface IXUserDevice : IUnknown
{
    HRESULT XUserFindForDevice( [in] const APP_LOCAL_DEVICE_ID *deviceId, [out] XUserHandle *handle );
    HRESULT XUserRegisterForDeviceAssociationChanged( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XUserDeviceAssociationChangedCallback *callback, [out] XTaskQueueRegistrationToken *token );
    boolean XUserUnregisterForDeviceAssociationChanged( [in] XTaskQueueRegistrationToken token, [in] boolean wait );
    HRESULT XUserGetDefaultAudioEndpointUtf16( [in] XUserLocalId user, [in] XUserDefaultAudioEndpointKind defaultAudioEndpointKind, [in] SIZE_T endpointIdUtf16Count, [out, string, length_is(endpointIdUtf16Count)] WCHAR endpointIdUtf16[*], [out, optional] SIZE_T *endpointIdUtf16Used );
    HRESULT XUserRegisterForDefaultAudioEndpointUtf16Changed( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XUserDefaultAudioEndpointUtf16ChangedCallback *callback, [out] XTaskQueueRegistrationToken *token );
    boolean XUserUnregisterForDefaultAudioEndpointUtf16Changed( [in] XTaskQueueRegistrationToken token, [in] boolean wait );
    HRESULT XUserFindControllerForUserWithUiAsync( [in] XUserHandle user, [in, out] XAsyncBlock *async );
    HRESULT XUserFindControllerForUserWithUiResult( [in, out] XAsyncBlock *async, [out] APP_LOCAL_DEVICE_ID *deviceId );
}

[ uuid(8836fe87-edb9-4fe3-8dad-05f0d2cd5b40) ]
coclass XGameRuntimeFeatureImpl
{
    [default] interface IXGameRuntimeFeature;
}

[ uuid(e349bd1a-fc20-4e40-b99c-4178cc6b409f) ]
coclass XSystemImpl
{
    [default] interface IXSystem;
}

[ uuid(b884675d-b738-4a9c-815d-9a9a1e0c6c9b) ]
coclass XSystemAnalyticsImpl
{
    [default] interface IXSystemAnalytics;
}

[ uuid(073b7dcb-1fcf-4030-94be-e3c9eb623428) ]
coclass XThreadingImpl
{
    [default] interface IXThreading;
}

[ uuid(01acd177-91f9-4763-a38e-ccbb55ce32e0) ]
coclass XUserImpl
{
    [default] interface IXUser;
    interface IXUserGamertag;
}

[ uuid(7d824997-10dc-45ab-86b7-2737767c0bf1) ]
coclass XUserDeviceImpl
{
    [default] interface IXUserDevice;
}
