/*
 * xgameruntime.dll implementation
 *
 * Copyright 2026 Olivia Ryan
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep header

import "propidl.idl";

cpp_quote("#if 0")
typedef struct APP_LOCAL_DEVICE_ID
{
    BYTE value[32];
} APP_LOCAL_DEVICE_ID;

typedef UINT64 time_t;
cpp_quote("#endif")

import "xgameruntime.h";

interface IXAccessibility;
interface IXAppCapture;
interface IXAppCapture2;
interface IXDisplay;
interface IErrorImpl1;
interface IXGame;
interface IGameActivationImpl1;
interface IXGameEvent;
interface IXGameInvite;
interface IGameProtocolImpl1;
interface IXGameRuntimeFeature;
interface IXGameSave;
interface IXLauncher;
interface IXPackage;
interface IXPersistentLocalStorage;
interface IStoreImpl1;
interface IStoreImpl2;
interface IStoreImpl3;
interface IStoreImpl4;
interface IStoreImpl5;
interface IStoreImpl6;
interface IXSystem;
interface IXSystemAnalytics;
interface IUserImpl1;
interface IUserImpl2;
interface IUserImpl3;
interface IUserImpl4;
interface IUserImpl5;
interface IUserImpl6;
interface IUserGamertagImpl;

coclass XAccessibilityImpl;
coclass XAppCaptureImpl;
coclass XAppCaptureImpl2;
coclass XDisplayImpl;
coclass XErrorImpl;
coclass XGameImpl;
coclass XGameActivationImpl;
coclass XGameEventImpl;
coclass XGameInviteImpl;
coclass XGameProtocolImpl;
coclass XGameRuntimeFeatureImpl;
coclass XGameSaveImpl;
coclass XLauncherImpl;
coclass XPackageImpl;
coclass XPersistentLocalStorageImpl;
coclass XStoreImpl;
coclass XSystemImpl;
coclass XSystemAnalyticsImpl;
coclass XUserImpl;

[
    local,
    object,
    uuid(d722b373-8c4d-4692-9e51-d6ad9b37aa7d)
]
interface IXAccessibility : IUnknown
{
    HRESULT XClosedCaptionGetProperties( [out] XClosedCaptionProperties *props );
    HRESULT XClosedCaptionSetEnabled( [in] BOOLEAN enabled );
    HRESULT XHighContrastGetMode( [out] XHighContrastMode *mode );
    HRESULT XSpeechToTextSetPositionHint( [in] XSpeechToTextPositionHint position );
    HRESULT XSpeechToTextSendString( [in, string] const char *speakerName, [in, string] const char *content, [in] XSpeechToTextType type );
    HRESULT XSpeechSynthesizerEnumerateInstalledVoices( [in, optional] void *context, [in] XSpeechSynthesizerInstalledVoicesCallback *callback );
    HRESULT XSpeechSynthesizerCreate( [out] XSpeechSynthesizerHandle *speechSynthesizer );
    HRESULT XSpeechSynthesizerCloseHandle( [in, optional] XSpeechSynthesizerHandle speechSynthesizer );
    HRESULT XSpeechSynthesizerSetDefaultVoice( [in] XSpeechSynthesizerHandle speechSynthesizer );
    HRESULT XSpeechSynthesizerSetCustomVoice( [in] XSpeechSynthesizerHandle speechSynthesizer, [in, string] const char *voiceId );
    HRESULT XSpeechSynthesizerCreateStreamFromText( [in] XSpeechSynthesizerHandle speechSynthesizer, [in, string] const char *text, [out] XSpeechSynthesizerStreamHandle *speechSynthesisStream );
    HRESULT XSpeechSynthesizerCloseStreamHandle( [in] XSpeechSynthesizerStreamHandle speechSynthesisStream );
    HRESULT XSpeechSynthesizerGetStreamDataSize( [in] XSpeechSynthesizerStreamHandle speechSynthesisStream, [out] SIZE_T *bufferSize );
    HRESULT XSpeechSynthesizerGetStreamData( [in] XSpeechSynthesizerStreamHandle speechSynthesisStream, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XSpeechToTextBeginHypothesisString( [in, string] const char *speakerName, [in, string] const char *content, [in] XSpeechToTextType type, [out] UINT32 *hypothesisId );
    HRESULT XSpeechToTextUpdateHypothesisString( [in] UINT32 hypothesisId, [in, string] const char *content );
    HRESULT XSpeechToTextFinalizeHypothesisString( [in] UINT32 hypothesisId, [in, string] const char *content );
    HRESULT XSpeechToTextCancelHypothesisString( [in] UINT32 hypothesisId );
    HRESULT XSpeechSynthesizerCreateStreamFromSsml( [in] XSpeechSynthesizerHandle speechSynthesizer, [in, string] const char *ssml, [out] XSpeechSynthesizerStreamHandle *speechSynthesisStream );
}

[
    local,
    object,
    uuid(186d5592-a72d-45fb-9560-11aed0e6647a)
]
interface IXAppCapture : IUnknown
{
    BOOLEAN XAppBroadcastIsAppBroadcasting();
    HRESULT XAppBroadcastShowUI( [in] XUserHandle requestingUser );
    HRESULT XAppBroadcastGetStatus( [in] XUserHandle requestingUser, [out] XAppBroadcastStatus *appBroadcastStatus );
    HRESULT XAppBroadcastRegisterIsAppBroadcastingChanged( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XAppBroadcastMonitorCallback *appBroadcastMonitorCallback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XAppBroadcastUnregisterIsAppBroadcastingChanged( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
    HRESULT XAppCaptureMetadataAddStringEvent( [in, string] const char *name, [in, string] const char *value, [in] XAppCaptureMetadataPriority priority );
    HRESULT XAppCaptureMetadataAddInt32Event( [in, string] const char *name, [in] INT32 value, [in] XAppCaptureMetadataPriority priority );
    HRESULT XAppCaptureMetadataAddDoubleEvent( [in, string] const char *name, [in] double value, [in] XAppCaptureMetadataPriority priority );
    HRESULT XAppCaptureMetadataStartStringState( [in, string] const char *name, [in, string] const char *value, [in] XAppCaptureMetadataPriority priority );
    HRESULT XAppCaptureMetadataStartInt32State( [in, string] const char *name, [in] INT32 value, [in] XAppCaptureMetadataPriority priority );
    HRESULT XAppCaptureMetadataStartDoubleState( [in, string] const char *name, [in] double value, [in] XAppCaptureMetadataPriority priority );
    HRESULT XAppCaptureMetadataStopState( [in, string] const char *name );
    HRESULT XAppCaptureMetadataStopAllStates();
    HRESULT XAppCaptureMetadataRemainingStorageBytesAvailable( [out] UINT64 *value );
    HRESULT XAppCaptureRegisterMetadataPurged( [in, optional] XTaskQueueHandle queue, [in] void *context, [in] XAppCaptureMetadataPurgedCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XAppCaptureUnRegisterMetadataPurged( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
}

[
    local,
    object,
    uuid(22e672d7-b4e3-406c-bd50-8f0d25236f9e)
]
interface IXAppCapture2 : IUnknown
{
    HRESULT XAppCaptureTakeDiagnosticScreenshot( [in] BOOLEAN gamescreenOnly, [in] XAppCaptureScreenshotFormatFlag captureFlags, [in, optional, string] const char *filenamePrefix, [out] XAppCaptureDiagnosticScreenshotResult *result );
    HRESULT XAppCaptureRecordDiagnosticClip( [in] time_t startTime, [in] UINT32 durationInMs, [in, optional, string] const char *filenamePrefix, [out] XAppCaptureRecordClipResult *result );
    HRESULT XAppCaptureTakeScreenshot( [in] XUserHandle requestingUser, [out] XAppCaptureTakeScreenshotResult *result );
    HRESULT XAppCaptureOpenScreenshotStream( [in, string] const char *localId, [in] XAppCaptureScreenshotFormatFlag screenshotFormat, [out] XAppCaptureScreenshotStreamHandle *handle, [out, optional] UINT64 *totalBytes );
    HRESULT XAppCaptureReadScreenshotStream( [in] XAppCaptureScreenshotStreamHandle handle, [in] UINT64 startPosition, [in] UINT32 bytesToRead, [out, size_is(bytesToRead)] UINT8 *buffer, [out] UINT32 *bytesWritten );
    HRESULT XAppCaptureCloseScreenshotStream( [in] XAppCaptureScreenshotStreamHandle handle );
    HRESULT XAppCaptureEnableRecord();
    HRESULT XAppCaptureDisableRecord();
    HRESULT XAppCaptureGetVideoCaptureSettings( [out] XAppCaptureVideoCaptureSettings *userCaptureSettings );
    HRESULT XAppCaptureRecordTimespan( [in, optional] const SYSTEMTIME *startTimestamp, [in] UINT64 durationInMilliseconds, [out] XAppCaptureLocalResult *result );
    HRESULT XAppCaptureReadLocalStream( [in] XAppCaptureLocalStreamHandle handle, [in] SIZE_T startPosition, [in] UINT32 bytesToRead, [out, size_is(bytesToRead)] UINT8 *buffer, [out] UINT32 *bytesWritten );
    HRESULT XAppCaptureCloseLocalStream( [in] XAppCaptureLocalStreamHandle handle );
    HRESULT XAppCaptureStartUserRecord( [in] XUserHandle requestingUser, [in] UINT32 localIdBufferLength, [out, string, size_is(localIdBufferLength)] char *localIdBuffer );
    HRESULT XAppCaptureStopUserRecord( [in, string] const char *localId, [out] XAppCaptureUserRecordingResult *result );
    HRESULT XAppCaptureCancelUserRecord( [in, string] const char *localId );
}

[
    local,
    object,
    uuid(35f07670-706e-4bfb-9476-090798c5ebf3)
]
interface IXDisplay : IUnknown
{
    HRESULT __PADDING__();
    XDisplayHdrModeResult XDisplayTryEnableHdrMode( [in] XDisplayHdrModePreference displayModePreference, [out, optional] XDisplayHdrModeInfo *displayHdrModeInfo );
}

[
    local,
    object,
    uuid(8ca467f7-22e8-4096-8456-bb8aa13f79d8)
]
interface IErrorImpl1 : IUnknown
{
    HRESULT __PADDING__();
    void    XErrorSetCallback( [in] XErrorCallback *callback, [in] void *context );
    void    XErrorSetOptions( XErrorOptions optionsDebuggerPresent, XErrorOptions optionsDebuggerNotPresent );
}

[
    local,
    object,
    uuid(2549f142-6419-4a06-97b5-931aab7c2f34)
]
interface IXGame : IUnknown
{
    HRESULT XGameGetXboxTitleId( [out] UINT32 *titleId );
    void    XLaunchNewGame( [in] const char *exePath, [in, optional] const char *args, [in, optional] XUserHandle defaultUser );
    HRESULT XLaunchRestartOnCrash( [in, optional] const char *args, [in] UINT32 reserved );
}

[
    local,
    object,
    uuid(2e4f76fe-0fc7-461e-ab4d-a4499434c3cf)
]
interface IGameActivationImpl1 : IUnknown
{
    HRESULT XGameActivationRegisterForEvent( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XGameActivationCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XGameActivationUnregisterForEvent( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
    HRESULT XGameActivationAcceptPendingInvite( [in, string] const char *inviteUri );
}

[
    local,
    object,
    uuid(bbfbdcc7-bfe7-409b-a5ca-edf054960b4d)
]
interface IXGameEvent : IUnknown
{
    HRESULT XGameEventWrite( [in] XUserHandle user, [in, string] const char *serviceConfigId, [in, string] const char *playSessionId, [in, string] const char *eventName, [in, optional, string] const char *dimensionsJson, [in, optional, string] const char *measurementsJson );
}

[
    local,
    object,
    uuid(0651aae2-4012-4077-bf84-8b9097090e2c)
]
interface IXGameInvite : IUnknown
{
    HRESULT XGameInviteRegisterForEvent( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XGameInviteEventCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XGameInviteUnregisterForEvent( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
}

[
    local,
    object,
    uuid(026b010c-06c3-4cdd-bbcb-43f229db1cff)
]
interface IGameProtocolImpl1 : IUnknown
{
    HRESULT XGameProtocolRegisterForActivation( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XGameProtocolActivationCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XGameProtocolUnregisterForActivation( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
}

[
    local,
    object,
    uuid(8836fe87-edb9-4fe3-8dad-05f0d2cd5b40)
]
interface IXGameRuntimeFeature : IUnknown
{
    BOOLEAN XGameRuntimeIsFeatureAvailable( [in] XGameRuntimeFeature feature );
}

[
    local,
    object,
    uuid(1bfff3af-f14a-40a3-8e35-9ada906593f9)
]
interface IXGameSave : IUnknown
{
    HRESULT XGameSaveInitializeProvider( [in] XUserHandle requestingUser, [in, string] const char *configurationId, [in] BOOLEAN syncOnDemand, [out] XGameSaveProviderHandle *provider );
    HRESULT XGameSaveInitializeProviderAsync( [in] XUserHandle requestingUser, [in, string] const char *configurationId, [in] BOOLEAN syncOnDemand, [in, out] XAsyncBlock *async );
    HRESULT XGameSaveInitializeProviderResult( [in, out] XAsyncBlock *async, [out] XGameSaveProviderHandle *provider );
    void    XGameSaveCloseProvider( [in] XGameSaveProviderHandle provider );
    HRESULT XGameSaveGetRemainingQuota( [in] XGameSaveProviderHandle provider, [out] INT64 *remainingQuota );
    HRESULT XGameSaveGetRemainingQuotaAsync( [in] XGameSaveProviderHandle provider, [in, out] XAsyncBlock *async );
    HRESULT XGameSaveGetRemainingQuotaResult( [in, out] XAsyncBlock *async, [out] INT64 *remainingQuota );
    HRESULT XGameSaveDeleteContainer( [in] XGameSaveProviderHandle provider, [in, string] const char *containerName );
    HRESULT XGameSaveDeleteContainerAsync( [in] XGameSaveProviderHandle provider, [in, string] const char *containerName, [in, out] XAsyncBlock *async );
    HRESULT XGameSaveDeleteContainerResult( [in, out] XAsyncBlock *async );
    HRESULT XGameSaveGetContainerInfo( [in] XGameSaveProviderHandle provider, [in, string] const char *containerName, [in, optional] void *context, [in] XGameSaveContainerInfoCallback *callback );
    HRESULT XGameSaveEnumerateContainerInfo( [in] XGameSaveProviderHandle provider, [in, optional] void *context, [in] XGameSaveContainerInfoCallback *callback );
    HRESULT XGameSaveEnumerateContainerInfoByName( [in] XGameSaveProviderHandle provider, [in, optional, string] const char *containerNamePrefix, [in, optional] void *context, [in] XGameSaveContainerInfoCallback *callback );
    HRESULT XGameSaveCreateContainer( [in] XGameSaveProviderHandle provider, [in, string] const char *containerName, [out] XGameSaveContainerHandle *containerContext );
    void    XGameSaveCloseContainer( [in] XGameSaveContainerHandle context );
    HRESULT XGameSaveEnumerateBlobInfo( [in] XGameSaveContainerHandle container, [in, optional] void *context, [in] XGameSaveBlobInfoCallback *callback );
    HRESULT XGameSaveEnumerateBlobInfoByName( [in] XGameSaveContainerHandle container, [in, optional, string] const char *blobNamePrefix, [in, optional] void *context, [in] XGameSaveBlobInfoCallback *callback );
    HRESULT XGameSaveReadBlobData( [in] XGameSaveContainerHandle container, [in, optional, string, size_is(countOfBlobs,)] const char **blobNames, [in, out] UINT32 *countOfBlobs, [in] SIZE_T blobsSize, [out, size_is(blobsSize)] XGameSaveBlob *blobData );
    HRESULT XGameSaveReadBlobDataAsync( [in] XGameSaveContainerHandle container, [in, optional, string, size_is(countOfBlobs,)] const char **blobNames, [in] UINT32 countOfBlobs, [in, out] XAsyncBlock *async );
    HRESULT XGameSaveReadBlobDataResult( [in, out] XAsyncBlock *async, [in] SIZE_T blobsSize, [out, size_is(blobsSize)] XGameSaveBlob *blobData, [out] UINT32 *countOfBlobs );
    HRESULT XGameSaveCreateUpdate( [in] XGameSaveContainerHandle container, [in, string] const char *containerDisplayName, [out] XGameSaveUpdateHandle *updateContext );
    void    XGameSaveCloseUpdate( [in] XGameSaveUpdateHandle context );
    HRESULT XGameSaveSubmitBlobWrite( [in] XGameSaveUpdateHandle updateContext, [in, string] const char *blobName, [in, size_is(byteCount)] UINT8 *data, [in] SIZE_T byteCount );
    HRESULT XGameSaveSubmitBlobDelete( [in] XGameSaveUpdateHandle updateContext, [in, string] const char *blobName );
    HRESULT XGameSaveSubmitUpdate( [in] XGameSaveUpdateHandle updateContext );
    HRESULT XGameSaveSubmitUpdateAsync( [in] XGameSaveUpdateHandle updateContext, [in, out] XAsyncBlock *async );
    HRESULT XGameSaveSubmitUpdateResult( [in, out] XAsyncBlock *async );
    HRESULT XGameSaveFilesGetFolderWithUiAsync( [in] XUserHandle requestingUser, [in, string] const char *configurationId, [in, out] XAsyncBlock *async );
    HRESULT XGameSaveFilesGetFolderWithUiResult( [in, out] XAsyncBlock *async, [in] SIZE_T folderSize, [out, size_is(folderSize)] char *folderResult );
    HRESULT XGameSaveFilesGetRemainingQuota( [in] XUserHandle userContext, [in, string] const char *configurationId, [out] INT64 *remainingQuota );
}

[
    local,
    object,
    uuid(1b339674-328d-4283-a200-3171f18d3639)
]
interface IXLauncher : IUnknown
{
    HRESULT XLaunchUri( [in, optional] XUserHandle user, [in, string] const char *uri );
    HRESULT XDisplayAcquireTimeoutDeferral( [out] XDisplayTimeoutDeferralHandle *handle );
    void    XDisplayCloseTimeoutDeferralHandle( [in] XDisplayTimeoutDeferralHandle handle );
}

[
    local,
    object,
    uuid(e2a4734b-2f4a-456d-aa8f-d065e04fb209)
]
interface IXPackage : IUnknown
{
    HRESULT XPackageGetCurrentProcessPackageIdentifier( [in] SIZE_T bufferSize, [out, size_is(bufferSize)] char *buffer );
    BOOLEAN XPackageIsPackagedProcess();
    HRESULT XPackageCreateInstallationMonitor( [in, string] const char *packageIdentifier, [in] UINT32 selectorCount, [in, optional, length_is(selectorCount)] XPackageChunkSelector selectors[*], [in] UINT32 minimumUpdateIntervalMs, [in, optional] XTaskQueueHandle queue, [out] XPackageInstallationMonitorHandle *installationMonitor );
    void    XPackageCloseInstallationMonitorHandle( [in] XPackageInstallationMonitorHandle installationMonitor );
    void    XPackageGetInstallationProgress( [in] XPackageInstallationMonitorHandle installationMonitor, [out] XPackageInstallationProgress *progress );
    BOOLEAN XPackageUpdateInstallationMonitor( [in] XPackageInstallationMonitorHandle installationMonitor );
    HRESULT XPackageRegisterInstallationProgressChanged( [in] XPackageInstallationMonitorHandle installationMonitor, [in, optional] void *context, [in] XPackageInstallationProgressCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XPackageUnregisterInstallationProgressChanged( [in] XPackageInstallationMonitorHandle installationMonitor, [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
    HRESULT XPackageGetUserLocale( [in] SIZE_T localeSize, [out, size_is(localSize)] char *locale );
    HRESULT XPackageFindChunkAvailability( [in, string] const char *packageIdentifier, [in] UINT32 selectorCount, [in, optional, length_is(selectorCount)] XPackageChunkSelector selectors[*], [out] XPackageChunkAvailability *availability );
    HRESULT XPackageEnumerateChunkAvailability( [in, string] const char *packageIdentifier, [in] XPackageChunkSelectorType type, [in] void *context, [in] XPackageChunkAvailabilityCallback *callback );
    HRESULT XPackageChangeChunkInstallOrder( [in, string] const char *packageIdentifier, [in] UINT32 selectorCount, [in, length_is(selectorCount)] XPackageChunkSelector selectors[*] );
    HRESULT XPackageInstallChunks( [in, string] const char *packageIdentifier, [in] UINT32 selectorCount, [in, size_is(selectorCount)] XPackageChunkSelector *selectors, [in] UINT32 minimumUpdateIntervalMs, [in] BOOLEAN suppressUserConfirmation, [in, optional] XTaskQueueHandle queue, [out] XPackageInstallationMonitorHandle *installationMonitor );
    HRESULT XPackageInstallChunksAsync( [in, string] const char *packageIdentifier, [in] UINT32 selectorCount, [in, length_is(selectorCount)] XPackageChunkSelector selectors[*], [in] UINT32 minimumUpdateIntervalMs, [in] BOOLEAN suppressUserConfirmation, [in, out] XAsyncBlock *asyncBlock );
    HRESULT XPackageInstallChunksResult( [in, out] XAsyncBlock *asyncBlock, [out] XPackageInstallationMonitorHandle *installationMonitor );
    HRESULT XPackageEstimateDownloadSize( [in, string] const char *packageIdentifier, [in] UINT32 selectorCount, [in, length_is(selectorCount)] XPackageChunkSelector selectors[*], [out] UINT64 *downloadSize, [out, optional] BOOLEAN *shouldPresentUserConfirmation );
    HRESULT XPackageUninstallChunks( [in, string] const char *packageIdentifier, [in] UINT32 selectorCount, [in, length_is(selectorCount)] XPackageChunkSelector selectors[*] );
    HRESULT __PADDING__();
    HRESULT __PADDING_2__();
    BOOLEAN XPackageUnregisterPackageInstalled( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
    HRESULT __PADDING_3__();
    HRESULT XPackageGetMountPathSize( [in] XPackageMountHandle mount, [out] SIZE_T *pathSize );
    HRESULT XPackageGetMountPath( [in] XPackageMountHandle mount, [in] SIZE_T pathSize, [out, size_is(pathSize)] char *path );
    void    XPackageCloseMountHandle( [in] XPackageMountHandle mount );
    HRESULT __PADDING_4__();
    HRESULT __PADDING_5__();
    HRESULT __PADDING_6__();
    HRESULT XPackageGetWriteStats( [out] XPackageWriteStats *writeStats );
    HRESULT __PADDING_7__();
    HRESULT XPackageUninstallUWPInstance( [in, string] const char *packageName );
    HRESULT XPackageEnumerateFeatures( [in, string] const char *packageIdentifier, [in, optional] void *context, [in] XPackageFeatureEnumerationCallback *callback );
    BOOLEAN XPackageUninstallPackage( [in, string] const char *packageIdentifier );
    HRESULT __PADDING_8__();
    HRESULT __PADDING_9__();
    HRESULT XPackageMountWithUiAsync( [in, string] const char *packageIdentifier, [in, out] XAsyncBlock *async );
    HRESULT XPackageMountWithUiResult( [in, out] XAsyncBlock *async, [out] XPackageMountHandle *mount );
    HRESULT XPackageEnumeratePackages( [in] XPackageKind kind, [in] XPackageEnumerationScope scope, [in, optional] void *context, [in] XPackageEnumerationCallback *callback );
    HRESULT XPackageRegisterPackageInstalled( [in] XTaskQueueHandle queue, [in, optional] void *context, [in] XPackageInstalledCallback *callback, [out] XTaskQueueRegistrationToken *token );

/*  HRESULT XPackageMount( [in, string] const char *packageIdentifier, [out] XPackageMountHandle *mount ); */
}

[
    local,
    object,
    uuid(41a4e10c-5a7e-41d9-8c37-37bde62a07d6)
]
interface IXPersistentLocalStorage : IUnknown
{
    HRESULT XPersistentLocalStorageGetPathSize( [out] SIZE_T *pathSize );
    HRESULT XPersistentLocalStorageGetPath( [in] SIZE_T pathSize, [out, string, size_is(pathSize)] char *path, [out, optional] SIZE_T *pathUsed );
    HRESULT XPersistentLocalStorageGetSpaceInfo( [out] XPersistentLocalStorageSpaceInfo *info );
    HRESULT XPersistentLocalStoragePromptUserForSpaceAsync( [in] UINT64 requestedBytes, [in, out] XAsyncBlock *asyncBlock );
    HRESULT XPersistentLocalStoragePromptUserForSpaceResult( [in, out] XAsyncBlock *asyncBlock );
    HRESULT XPersistentLocalStorageMountForPackage( [in, string] const char *packageIdentifier, [out] XPackageMountHandle *mountHandle );
}

[
    local,
    object,
    uuid(b09d803c-2414-4a05-82c6-66dfdc9e9a44)
]
interface IStoreImpl1 : IUnknown
{
    HRESULT XStoreCreateContext( [in, optional] const XUserHandle user, [out] XStoreContextHandle *storeContextHandle );
    void    XStoreCloseContextHandle( [in] XStoreContextHandle storeContextHandle );
    HRESULT XStoreQueryAssociatedProductsAsync( [in] const XStoreContextHandle storeContextHandle, [in] XStoreProductKind productKinds, [in] UINT32 maxItemsToRetrievePerPage, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryAssociatedProductsResult( [in, out] XAsyncBlock *async, [out] XStoreProductQueryHandle *productQueryHandle );
    HRESULT XStoreQueryProductsAsync( [in] const XStoreContextHandle storeContextHandle, [in] XStoreProductKind productKinds, [in, string, size_is(storeIdsCount,)] const char **storeIds, [in] SIZE_T storeIdsCount, [in, optional, string, size_is(actionFiltersCount,)] const char **actionFilters, [in] SIZE_T actionFiltersCount, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryProductsResult( [in, out] XAsyncBlock *async, [out] XStoreProductQueryHandle *productQueryHandle );
    HRESULT XStoreQueryEntitledProductsAsync( [in] const XStoreContextHandle storeContextHandle, [in] XStoreProductKind productKinds, [in] UINT32 maxItemsToRetrievePerPage, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryEntitledProductsResult( [in, out] XAsyncBlock *async, [out] XStoreProductQueryHandle *productQueryHandle );
    HRESULT XStoreQueryProductForCurrentGameAsync( [in] const XStoreContextHandle storeContextHandle, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryProductForCurrentGameResult( [in, out] XAsyncBlock *async, [out] XStoreProductQueryHandle *productQueryHandle );
    HRESULT XStoreQueryProductForPackageAsync( [in] const XStoreContextHandle storeContextHandle, [in] XStoreProductKind productKinds, [in, string] const char *packageIdentifier, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryProductForPackageResult( [in, out] XAsyncBlock *async, [out] XStoreProductQueryHandle *productQueryHandle );
    HRESULT XStoreEnumerateProductsQuery( [in] const XStoreProductQueryHandle productQueryHandle, [in, optional] void *context, [in] XStoreProductQueryCallback *callback );
    BOOLEAN XStoreProductsQueryHasMorePages( [in] const XStoreProductQueryHandle productQueryHandle );
    HRESULT XStoreProductsQueryNextPageAsync( [in] const XStoreProductQueryHandle productQueryHandle, [in, out] XAsyncBlock *async );
    HRESULT XStoreProductsQueryNextPageResult( [in, out] XAsyncBlock *async, [out] XStoreProductQueryHandle *productQueryHandle );
    void    XStoreCloseProductsQueryHandle( [in] XStoreProductQueryHandle productQueryHandle );
    HRESULT XStoreAcquireLicenseForPackageAsync( [in] const XStoreProductQueryHandle productQueryHandle, [in, string] const char *packageIdentifier, [in, out] XAsyncBlock *async );
    HRESULT XStoreAcquireLicenseForPackageResult( [in, out] XAsyncBlock *async, [out] XStoreLicenseHandle *storeLicenseHandle );
    BOOLEAN XStoreIsLicenseValid( [in] const XStoreLicenseHandle storeLicenseHandle );
    void    XStoreCloseLicenseHandle( [in] XStoreLicenseHandle storeLicenseHandle );
    HRESULT XStoreCanAcquireLicenseForStoreIdAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *storeProductId, [in, out] XAsyncBlock *async );
    HRESULT XStoreCanAcquireLicenseForStoreIdResult( [in, out] XAsyncBlock *async, [out] XStoreCanAcquireLicenseResult *storeCanAcquireLicense );
    HRESULT XStoreCanAcquireLicenseForPackageAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *packageIdentifier, [in, out] XAsyncBlock *async );
    HRESULT XStoreCanAcquireLicenseForPackageResult( [in, out] XAsyncBlock *async, [out] XStoreCanAcquireLicenseResult *storeCanAcquireLicense );
    HRESULT XStoreQueryGameLicenseAsync( [in] const XStoreContextHandle storeContextHandle, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryGameLicenseResult( [in, out] XAsyncBlock *async, [out] XStoreGameLicense *license );
    HRESULT XStoreQueryAddOnLicensesAsync( [in] const XStoreContextHandle storeContextHandle, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryAddOnLicensesResultCount( [in, out] XAsyncBlock *async, [out] UINT32 *count );
    HRESULT XStoreQueryAddOnLicensesResult( [in, out] XAsyncBlock *async, [in] UINT32 count, [out, length_is(count)] XStoreAddonLicense addOnLicenses[*] );
    HRESULT XStoreQueryConsumableBalanceRemainingAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *storeProductId, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryConsumableBalanceRemainingResult( [in, out] XAsyncBlock *async, [out] XStoreConsumableResult *consumableResult );
    HRESULT XStoreReportConsumableFulfillmentAsync( [in, out] const XStoreContextHandle storeContextHandle, [in, string] const char *storeProductId, [in] UINT32 quantity, [in] GUID trackingId, [in, out] XAsyncBlock *async );
    HRESULT XStoreReportConsumableFulfillmentResult( [in, out] XAsyncBlock *async, [out] XStoreConsumableResult *consumableResult );
    HRESULT XStoreGetUserCollectionsIdAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *serviceTicket, [in, string] const char *publisherUserId, [in, out] XAsyncBlock *async );
    HRESULT XStoreGetUserCollectionsIdResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *size );
    HRESULT XStoreGetUserCollectionsIdResult( [in, out] XAsyncBlock *async, [in] SIZE_T size, [out, string, size_is(size)] char *result );
    HRESULT XStoreGetUserPurchaseIdAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *serviceTicket, [in, string] const char *publisherUserId, [in, out] XAsyncBlock *async );
    HRESULT XStoreGetUserPurchaseIdResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *size );
    HRESULT XStoreGetUserPurchaseIdResult( [in, out] XAsyncBlock *async, [in] SIZE_T size, [out, string, size_is(size)] char *result );
    HRESULT XStoreQueryLicenseTokenAsync( [in] const XStoreContextHandle storeContextHandle, [in, string, size_is(productIdsCount,)] const char **productIds, [in] SIZE_T productIdsCount, [in, string] const char *customDeveloperString, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryLicenseTokenResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *size );
    HRESULT XStoreQueryLicenseTokenResult( [in, out] XAsyncBlock *async, [in] SIZE_T size, [out, string, size_is(size)] char *result );
    HRESULT __PADDING__();
    HRESULT __PADDING_2__();
    HRESULT __PADDING_3__();
    HRESULT XStoreShowPurchaseUIAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *storeId, [in, optional, string] const char *name, [in, optional, string] const char *extendedJsonData, [in, out] XAsyncBlock *async );
    HRESULT XStoreShowPurchaseUIResult( [in, out] XAsyncBlock *async );
    HRESULT XStoreShowRateAndReviewUIAsync( [in] const XStoreContextHandle storeContextHandle, [in, out] XAsyncBlock *async );
    HRESULT XStoreShowRateAndReviewUIResult( [in, out] XAsyncBlock *async, [out] XStoreRateAndReviewResult *result );
    HRESULT XStoreShowRedeemTokenUIAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *token, [in, string, size_is(allowedStoreIdsCount,)] const char **allowedStoreIds, [in] SIZE_T allowedStoreIdsCount, [in] BOOLEAN disallowCsvRedemption, [in, out] XAsyncBlock *async );
    HRESULT XStoreShowRedeemTokenUIResult( [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryGameAndDlcPackageUpdatesAsync( [in] const XStoreContextHandle storeContextHandle, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryGameAndDlcPackageUpdatesResultCount( [in, out] XAsyncBlock *async, [out] UINT32 *count );
    HRESULT XStoreQueryGameAndDlcPackageUpdatesResult( [in, out] XAsyncBlock *async, [in] UINT32 count, [out, length_is(count)] XStorePackageUpdate packageUpdates[*] );
    HRESULT XStoreDownloadPackageUpdatesAsync( [in] const XStoreContextHandle storeContextHandle, [in, string, size_is(packageIdentifiersCount,)] const char **packageIdentifiers, [in] SIZE_T packageIdentifiersCount, [in, out] XAsyncBlock *async );
    HRESULT XStoreDownloadPackageUpdatesResult( [in, out] XAsyncBlock *async );
    HRESULT XStoreDownloadAndInstallPackageUpdatesAsync( [in] const XStoreContextHandle storeContextHandle, [in, string, size_is(packageIdentifiersCount,)] const char **packageIdentifiers, [in] SIZE_T packageIdentifiersCount, [in, out] XAsyncBlock *async );
    HRESULT XStoreDownloadAndInstallPackageUpdatesResult( [in, out] XAsyncBlock *async );
    HRESULT XStoreDownloadAndInstallPackagesAsync( [in] const XStoreContextHandle storeContextHandle, [in, string, size_is(storeIdsCount,)] const char **storeIds, [in] SIZE_T storeIdsCount, [in, out] XAsyncBlock *async );
    HRESULT XStoreDownloadAndInstallPackagesResultCount( [in, out] XAsyncBlock *async, [out] UINT32 *count );
    HRESULT XStoreDownloadAndInstallPackagesResult( [in, out] XAsyncBlock *async, [in] UINT32 count, [out, string, size_is(count,33)] char **packageIdentifiers );
    HRESULT XStoreQueryPackageIdentifier( [in, string] const char *storeId, [in] SIZE_T size, [out, string, size_is(size)] char *packageIdentifier );
    HRESULT XStoreRegisterGameLicenseChanged( [in] XStoreContextHandle storeContextHandle, [in] XTaskQueueHandle queue, [in, optional] void *context, [in] XStoreGameLicenseChangedCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XStoreUnregisterGameLicenseChanged( [in] XStoreContextHandle storeContextHandle, [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
    HRESULT XStoreRegisterPackageLicenseLost( [in] XStoreLicenseHandle licenseHandle, [in] XTaskQueueHandle queue, [in, optional] void *context, [in] XStorePackageLicenseLostCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XStoreUnregisterPackageLicenseLost( [in] XStoreLicenseHandle licenseHandle, [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
}

[
    local,
    object,
    uuid(60b09f4e-1b85-45b1-826c-169118e230e1)
]
interface IStoreImpl2 : IStoreImpl1
{
    BOOLEAN XStoreIsAvailabilityPurchasable( [in] const XStoreAvailability availability );
}

[
    local,
    object,
    uuid(2d42fea5-e71d-4b76-97cd-c50afbb3ae5d)
]
interface IStoreImpl3 : IStoreImpl2
{
    HRESULT XStoreAcquireLicenseForDurablesAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *storeId, [in, out] XAsyncBlock *async );
    HRESULT XStoreAcquireLicenseForDurablesResult( [in, out] XAsyncBlock *async, [out] XStoreLicenseHandle *storeLicenseHandle );
}

[
    local,
    object,
    uuid(b09d803c-2414-4a05-82c6-66dfdc9e9a44)
]
interface IStoreImpl4 : IStoreImpl3
{
    HRESULT XStoreShowAssociatedProductsUIAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *storeId, [in] XStoreProductKind productKinds, [in, out] XAsyncBlock *async );
    HRESULT XStoreShowAssociatedProductsUIResult( [in, out] XAsyncBlock *async );
    HRESULT XStoreShowProductPageUIAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *storeId, [in, out] XAsyncBlock *async );
    HRESULT XStoreShowProductPageUIResult( [in, out] XAsyncBlock *async );
}

[
    local,
    object,
    uuid(5c48dedf-0b67-4492-a4b5-6829b8e796e1)
]
interface IStoreImpl5 : IStoreImpl4
{
    HRESULT XStoreQueryAssociatedProductsForStoreIdAsync( [in] const XStoreContextHandle storeContextHandle, [in, string] const char *storeId, [in] XStoreProductKind productKinds, [in] UINT32 maxItemsToRetrievePerPage, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryAssociatedProductsForStoreIdResult( [in, out] XAsyncBlock *async, [out] XStoreProductQueryHandle *productQueryHandle );
    HRESULT XStoreQueryPackageUpdatesAsync( [in] XStoreContextHandle storeContextHandle, [in, string, size_is(packageIdentifiersCount,)] const char **packageIdentifiers, [in] SIZE_T packageIdentifiersCount, [in, out] XAsyncBlock *async );
    HRESULT XStoreQueryPackageUpdatesResultCount( [in, out] XAsyncBlock *async, [out] UINT32 *count );
    HRESULT XStoreQueryPackageUpdatesResult( [in, out] XAsyncBlock *async, [in] UINT32 count, [out, length_is(count)] XStorePackageUpdate packageUpdates[*] );
}

[
    local,
    object,
    uuid(b09d803c-2414-4a05-82c6-66dfdc9e9a44)
]
interface IStoreImpl6 : IStoreImpl5
{
    HRESULT XStoreShowGiftingUIAsync( [in] XStoreContextHandle storeContextHandle, [in, string] const char *storeId, [in, optional, string] const char *name, [in, optional, string] const char *extendedJsonData, [in, out] XAsyncBlock *async );
    HRESULT XStoreShowGiftingUIResult( [in, out] XAsyncBlock *async );
}

[
    local,
    object,
    uuid(dadc2895-34b0-4ef5-a83e-45114d629b80)
]
interface IXSystem : IUnknown
{
    HRESULT XSystemGetConsoleId( [in] INT32 consoleIdSize, [out, size_is(consoleIdSize)] char *consoleId, [out, optional] SIZE_T *consoleIdUsed );
    HRESULT XSystemGetXboxLiveSandboxId( [in] INT32 sandboxIdSize, [out, size_is(sandboxIdSize)] char *sandboxId, [out] SIZE_T *sandboxIdUsed );
    HRESULT XSystemGetAppSpecificDeviceId( [in] INT32 appSpecificDeviceIdSize, [out, size_is(appSpecificDeviceIdSize)] char *appSpecificDeviceId, [out, optional] SIZE_T *appSpecificDeviceIdUsed );
    HRESULT XSystemHandleTrack( [in] XSystemHandleCallback callback, [in, optional] void *context );
    BOOLEAN XSystemIsHandleValid( [in] XSystemHandle handle );
    HRESULT XSystemAllowFullDownloadBandwidth( [in] BOOLEAN enable );
}

[
    local,
    object,
    uuid(b884675d-b738-4a9c-815d-9a9a1e0c6c9b)
]
interface IXSystemAnalytics : IUnknown
{
    XSystemAnalyticsInfo XSystemGetAnalyticsInfo();
}

[
    local,
    object,
    uuid(01acd177-91f9-4763-a38e-ccbb55ce32e0)
]
interface IUserImpl1 : IUnknown
{
    HRESULT XUserDuplicateHandle( [in] XUserHandle handle, [out] XUserHandle *duplicatedHandle );
    void    XUserCloseHandle( [in] XUserHandle user );
    INT32   XUserCompare( [in, optional] XUserHandle user1, [in, optional] XUserHandle user2 );
    HRESULT XUserGetMaxUsers( [out] UINT32 *maxUsers );
    HRESULT XUserAddAsync( [in] XUserAddOptions options, [in, out] XAsyncBlock *async );
    HRESULT XUserAddResult( [in, out] XAsyncBlock *async, [out] XUserHandle *newUser );
    HRESULT XUserGetLocalId( [in] XUserHandle user, [out] XUserLocalId *userLocalId );
    HRESULT XUserFindUserByLocalId( [in] XUserLocalId userLocalId, [out] XUserHandle *handle );
    HRESULT XUserGetId( [in] XUserHandle user, [out] UINT64 *userId );
    HRESULT XUserFindUserById( [in] UINT64 userId, [out] XUserHandle *handle );
    HRESULT XUserGetIsGuest( [in] XUserHandle user, [out] BOOLEAN *isGuest );
    HRESULT XUserGetState( [in] XUserHandle user, [out] XUserState *state );
    HRESULT __PADDING__();
    HRESULT XUserGetGamerPictureAsync( [in] XUserHandle user, [in] XUserGamerPictureSize pictureSize, [in, out] XAsyncBlock *async );
    HRESULT XUserGetGamerPictureResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *bufferSize );
    HRESULT XUserGetGamerPictureResult( [in, out] XAsyncBlock *async, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XUserGetAgeGroup( [in] XUserHandle user, [out] XUserAgeGroup *ageGroup );
    HRESULT XUserCheckPrivilege( [in] XUserHandle user, [in] XUserPrivilegeOptions options, [in] XUserPrivilege privilege, [out] BOOLEAN *hasPrivilege, [out, optional] XUserPrivilegeDenyReason *reason );
    HRESULT XUserResolvePrivilegeWithUiAsync( [in] XUserHandle user, [in] XUserPrivilegeOptions options, [in] XUserPrivilege privilege, [in, out] XAsyncBlock *async );
    HRESULT XUserResolvePrivilegeWithUiResult( [in, out] XAsyncBlock *async );
    HRESULT XUserGetTokenAndSignatureAsync( [in] XUserHandle user, [in] XUserGetTokenAndSignatureOptions options, [in, string] const char *method, [in, string] const char *url, [in] SIZE_T headerCount, [in, optional, length_is(headerCount)] const XUserGetTokenAndSignatureHttpHeader headers[*], [in] SIZE_T bodySize, [in, optional, size_is(bodySize)] const void *bodyBuffer, [in, out] XAsyncBlock *async );
    HRESULT XUserGetTokenAndSignatureResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *bufferSize );
    HRESULT XUserGetTokenAndSignatureResult( [in, out] XAsyncBlock *async, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out] XUserGetTokenAndSignatureData **ptrToBuffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XUserGetTokenAndSignatureUtf16Async( [in] XUserHandle user, [in] XUserGetTokenAndSignatureOptions options, [in, string] const WCHAR *method, [in, string] const WCHAR *url, [in] SIZE_T headerCount, [in, optional, length_is(headerCount)] const XUserGetTokenAndSignatureUtf16HttpHeader headers[*], [in] SIZE_T bodySize, [in, optional, size_is(bodySize)] const void *bodyBuffer, [in, out] XAsyncBlock *async );
    HRESULT XUserGetTokenAndSignatureUtf16ResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *bufferSize );
    HRESULT XUserGetTokenAndSignatureUtf16Result( [in, out] XAsyncBlock *async, [in] SIZE_T bufferSize, [out, size_is(bufferSize)] void *buffer, [out] XUserGetTokenAndSignatureUtf16Data **ptrToBuffer, [out, optional] SIZE_T *bufferUsed );
    HRESULT XUserResolveIssueWithUiAsync( [in] XUserHandle user, [in, optional, string] const char *url, [in, out] XAsyncBlock *async );
    HRESULT XUserResolveIssueWithUiResult( [in, out] XAsyncBlock *async );
    HRESULT XUserResolveIssueWithUiUtf16Async( [in] XUserHandle user, [in, optional, string] const WCHAR *url, [in, out] XAsyncBlock *async );
    HRESULT XUserResolveIssueWithUiUtf16Result( [in, out] XAsyncBlock *async );
    HRESULT XUserRegisterForChangeEvent( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XUserChangeEventCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XUserUnregisterForChangeEvent( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
    HRESULT XUserGetSignOutDeferral( [out] XUserSignOutDeferralHandle *deferral );
    void    XUserCloseSignOutDeferralHandle( [in] XUserSignOutDeferralHandle deferral );
}

[
    local,
    object,
    uuid(eb9bf948-18dc-4d82-bbcc-40e0a809c4c0)
]
interface IUserImpl2 : IUserImpl1
{
    HRESULT XUserAddByIdWithUiAsync( [in] UINT64 userId, [in, out] XAsyncBlock *async );
    HRESULT XUserAddByIdWithUiResult( [in, out] XAsyncBlock *async, [out] XUserHandle *newUser );
}

[
    local,
    object,
    uuid(1bf2f8c5-d507-4e52-bb05-f726d0e71161)
]
interface IUserImpl3 : IUserImpl2
{
    HRESULT XUserGetMsaTokenSilentlyAsync( [in] XUserHandle user, [in] XUserGetMsaTokenSilentlyOptions options, [in, string] const char *scope, [in, out] XAsyncBlock *async );
    HRESULT XUserGetMsaTokenSilentlyResult( [in, out] XAsyncBlock *async, [in] SIZE_T resultTokenSize, [out, string, size_is(resultTokenSize)] char *resultToken, [out, optional] SIZE_T *resultTokenUsed );
    HRESULT XUserGetMsaTokenSilentlyResultSize( [in, out] XAsyncBlock *async, [out] SIZE_T *tokenSize );
}

[
    local,
    object,
    uuid(079415e3-6727-437f-8e9d-8f8f9b2439f7)
]
interface IUserImpl4 : IUserImpl3
{
    BOOLEAN XUserIsStoreUser( [in] XUserHandle user );
}

[
    local,
    object,
    uuid(26f3c674-a2fe-44fa-b6c4-a323bc94ff53)
]
interface IUserImpl5 : IUserImpl4
{
    HRESULT XUserPlatformRemoteConnectSetEventHandlers( [in, optional] XTaskQueueHandle queue, [in] XUserPlatformRemoteConnectEventHandlers *handlers );
    HRESULT XUserPlatformRemoteConnectCancelPrompt( [in] XUserPlatformOperation operation );
    HRESULT XUserPlatformSpopPromptSetEventHandlers( [in, optional] XTaskQueueHandle queue, [in] XUserPlatformSpopPromptEventHandler *handler, [in, optional] void *context );
    HRESULT XUserPlatformSpopPromptComplete( [in] XUserPlatformOperation operation, [in] XUserPlatformOperationResult result );
}

[
    local,
    object,
    uuid(5131d685-4394-4ee6-8c18-bfb5d4aef1ff)
]
interface IUserImpl6 : IUserImpl5
{
    BOOLEAN XUserIsSignOutPresent();
    HRESULT XUserSignOutAsync( [in] XUserHandle user, [in, out] XAsyncBlock *async );
    HRESULT XUserSignOutResult( [in, out] XAsyncBlock *async );
}

[
    local,
    object,
    uuid(cef4fac0-7676-4a94-a119-4c43f9eb5b74)
]
interface IUserGamertagImpl : IUnknown
{
    HRESULT XUserGetGamertag( [in] XUserHandle user, [in] XUserGamertagComponent gamertagComponent, [in] SIZE_T gamertagSize, [out, string, size_is(gamertagSize)] char *gamertag, [out, optional] SIZE_T *gamertagUsed );
}

[
    uuid(3e241977-6237-41e9-8559-102c2d9983f1)
]
coclass XAccessibilityImpl
{
    [default] interface IXAccessibility;
}

[
    uuid(186d5592-a72d-45fb-9560-11aed0e6647a)
]
coclass XAppCaptureImpl
{
    [default] interface IXAppCapture;
}

[
    uuid(a4f1aee2-4bf1-4485-b008-a7c26d52ac27)
]
coclass XAppCaptureImpl2
{
    [default] interface IXAppCapture2;
}

[
    uuid(03f0fe74-fdd9-4e5c-b630-f9339c47acc5)
]
coclass XDisplayImpl
{
    [default] interface IXDisplay;
}

[
    uuid(8ca467f7-22e8-4096-8456-bb8aa13f79d8)
]
coclass XErrorImpl
{
    [default] interface IErrorImpl1;
}

[
    uuid(973a344e-24bf-4d0f-8457-56c534892b29)
]
coclass XGameImpl
{
    [default] interface IXGame;
}

[
    uuid(7f0fe8b8-e075-49ab-9aa7-a1e065489a9e)
]
coclass XGameActivationImpl
{
    [default] interface IGameActivationImpl1;
}

[
    uuid(bbfbdcc7-bfe7-409b-a5ca-edf054960b4d)
]
coclass XGameEventImpl
{
    [default] interface IXGameEvent;
}

[
    uuid(0651aae2-4012-4077-bf84-8b9097090e2c)
]
coclass XGameInviteImpl
{
    [default] interface IXGameInvite;
}

[
    uuid(95fd18d2-74dd-4d7c-aa1b-0b51827665d6)
]
coclass XGameProtocolImpl
{
    [default] interface IGameProtocolImpl1;
}

[
    uuid(8836fe87-edb9-4fe3-8dad-05f0d2cd5b40)
]
coclass XGameRuntimeFeatureImpl
{
    [default] interface IXGameRuntimeFeature;
}

[
    uuid(704c3f58-e629-4cc2-b197-30511b996fe2)
]
coclass XGameSaveImpl
{
    [default] interface IXGameSave;
}

[
    uuid(1b339674-328d-4283-a200-3171f18d3639)
]
coclass XLauncherImpl
{
    [default] interface IXLauncher;
}

[
    uuid(af406016-e850-4aa8-a88d-2f3dcb9dac7e)
]
coclass XPackageImpl
{
    [default] interface IXPackage;
}

[
    uuid(f4faf4d4-2d04-4fce-b3e0-474a713a3e84)
]
coclass XPersistentLocalStorageImpl
{
    [default] interface IXPersistentLocalStorage;
}

[
    uuid(0dd112ac-7c24-448c-b92b-3960fb5bd30c)
]
coclass XStoreImpl
{
    [default] interface IStoreImpl6;
}

[
    uuid(e349bd1a-fc20-4e40-b99c-4178cc6b409f)
]
coclass XSystemImpl
{
    [default] interface IXSystem;
}

[
    uuid(b884675d-b738-4a9c-815d-9a9a1e0c6c9b)
]
coclass XSystemAnalyticsImpl
{
    [default] interface IXSystemAnalytics;
}

[
    uuid(01acd177-91f9-4763-a38e-ccbb55ce32e0)
]
coclass XUserImpl
{
    [default] interface IUserImpl;
    interface IUserGamertagImpl;
}
