/*
 * Copyright (C) the Wine project
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

import "propidl.idl";

typedef void *XUserPlatformOperation;
typedef void *XUserHandle;
typedef void *XUserSignOutDeferralHandle;
typedef enum XUserAddOptions XUserAddOptions;
typedef enum XUserAgeGroup XUserAgeGroup;
typedef enum XUserChangeEvent XUserChangeEvent;
typedef enum XUserDefaultAudioEndpointKind XUserDefaultAudioEndpointKind;
typedef enum XUserGamerPictureSize XUserGamerPictureSize;
typedef enum XUserGamertagComponent XUserGamertagComponent;
typedef enum XUserGetMsaTokenSilentlyOptions XUserGetMsaTokenSilentlyOptions;
typedef enum XUserGetTokenAndSignatureOptions XUserGetTokenAndSignatureOptions;
typedef enum XUserPrivilege XUserPrivilege;
typedef enum XUserPrivilegeDenyReason XUserPrivilegeDenyReason;
typedef enum XUserPrivilegeOptions XUserPrivilegeOptions;
typedef enum XUserState XUserState;
typedef enum XUserPlatformOperationResult XUserPlatformOperationResult;
typedef enum XUserPlatformSpopOperationResult XUserPlatformSpopOperationResult;
cpp_quote("#if 0")
typedef struct APP_LOCAL_DEVICE_ID APP_LOCAL_DEVICE_ID;
cpp_quote("#endif")
typedef struct XUserDeviceAssociationChange XUserDeviceAssociationChange;
typedef struct XUserGetTokenAndSignatureData XUserGetTokenAndSignatureData;
typedef struct XUserGetTokenAndSignatureHttpHeader XUserGetTokenAndSignatureHttpHeader;
typedef struct XUserGetTokenAndSignatureUtf16Data XUserGetTokenAndSignatureUtf16Data;
typedef struct XUserGetTokenAndSignatureUtf16HttpHeader XUserGetTokenAndSignatureUtf16HttpHeader;
typedef struct XUserLocalId XUserLocalId;
typedef struct XUserPlatformRemoteConnectEventHandlers XUserPlatformRemoteConnectEventHandlers;
typedef void __stdcall XUserChangeEventCallback( void *context, XUserLocalId userLocalId, XUserChangeEvent event );
typedef void __stdcall XUserDefaultAudioEndpointUtf16ChangedCallback( void *context, XUserLocalId userLocalId, XUserDefaultAudioEndpointKind defaultAudioEndpointKind, const WCHAR *endpointIdUtf16 );
typedef void __stdcall XUserDeviceAssociationChangedCallback( void *context, const XUserDeviceAssociationChange *change );
typedef void __stdcall XUserPlatformRemoteConnectShowPromptEventHandler( void *context, UINT32 userIdentifier, XUserPlatformOperation operation, const CHAR *url, const CHAR *code, SIZE_T qrCodeSize, const void *qrCode );
typedef void __stdcall XUserPlatformRemoteConnectClosePromptEventHandler( void *context, UINT32 userIdentifier, XUserPlatformOperation operation );
typedef void __stdcall XUserPlatformSpopPromptEventHandler( void *context, UINT32 userIdentifier, XUserPlatformOperation operation, const CHAR *modernGamertag, const CHAR *modernGamertagSuffix );

enum XUserAddOptions
{
    XUserAddOptions_None                        = 0,
    XUserAddOptions_AddDefaultUserSilently      = 1,
    XUserAddOptions_AllowGuests                 = 2,
    XUserAddOptions_AddDefaultUserAllowingUI    = 4
};

enum XUserAgeGroup
{
    XUserAgeGroup_Unknown   = 0,
    XUserAgeGroup_Child     = 1,
    XUserAgeGroup_Teen      = 2,
    XUserAgeGroup_Adult     = 3
};

enum XUserChangeEvent
{
    XUserChangeEvent_SignedInAgain  = 0,
    XUserChangeEvent_SigningOut     = 1,
    XUserChangeEvent_SignedOut      = 2,
    XUserChangeEvent_Gamertag       = 3,
    XUserChangeEvent_GamerPicture   = 4,
    XUserChangeEvent_Privileges     = 5
};

enum XUserDefaultAudioEndpointKind
{
    XUserDefaultAudioEndpointKind_CommunicationRender   = 0,
    XUserDefaultAudioEndpointKind_CommunicationCapture  = 1
};

enum XUserGamerPictureSize
{
    XUserGamerPictureSize_Small         = 0,
    XUserGamerPictureSize_Medium        = 1,
    XUserGamerPictureSize_Large         = 2,
    XUserGamerPictureSize_ExtraLarge    = 3
};

enum XUserGamertagComponent
{
    XUserGamertagComponent_Classic      = 0,
    XUserGamertagComponent_Modern       = 1,
    XUserGamertagComponent_ModernSuffix = 2,
    XUserGamertagComponent_UniqueModern = 3
};

enum XUserGetMsaTokenSilentlyOptions
{
    XUserGetMsaTokenSilentlyOptions_None    = 0
};

enum XUserGetTokenAndSignatureOptions
{
    XUserGetTokenAndSignatureOptions_None           = 0,
    XUserGetTokenAndSignatureOptions_ForceRefresh   = 1,
    XUserGetTokenAndSignatureOptions_AllUsers       = 2
};

enum XUserPrivilege
{
    XUserPrivilege_CrossPlay            = 185,
    XUserPrivilege_Clubs                = 188,
    XUserPrivilege_Sessions             = 189,
    XUserPrivilege_Broadcast            = 190,
    XUserPrivilege_ManageProfilePrivacy = 196,
    XUserPrivilege_GameDvr              = 198,
    XUserPrivilege_MultiplayerParties   = 203,
    XUserPrivilege_CloudManageSession   = 207,
    XUserPrivilege_CloudJoinSession     = 208,
    XUserPrivilege_CloudSavedGames      = 209,
    XUserPrivilege_SocialNetworkSharing = 220,
    XUserPrivilege_UserGeneratedContent = 247,
    XUserPrivilege_Communications       = 252,
    XUserPrivilege_Multiplayer          = 254,
    XUserPrivilege_AddFriends           = 255
};

enum XUserPrivilegeDenyReason
{
    XUserPrivilegeDenyReason_None               = 0,
    XUserPrivilegeDenyReason_PurchaseRequired   = 1,
    XUserPrivilegeDenyReason_Restricted         = 2,
    XUserPrivilegeDenyReason_Banned             = 3,
    XUserPrivilegeDenyReason_Unknown            = -1
};

enum XUserPrivilegeOptions
{
    XUserPrivilegeOptions_None      = 0,
    XUserPrivilegeOptions_AllUsers  = 1
};

enum XUserState
{
    XUserState_SignedIn     = 0,
    XUserState_SigningOut   = 1,
    XUserState_SignedOut    = 2
};

enum XUserPlatformOperationResult
{
    XUserPlatformOperationResult_Success    = 0,
    XUserPlatformOperationResult_Failure    = 1,
    XUserPlatformOperationResult_Canceled   = 2
};

enum XUserPlatformSpopOperationResult
{
    XUserPlatformSpopOperationResult_SignInHere     = 0,
    XUserPlatformSpopOperationResult_SwitchAccount  = 1,
    XUserPlatformSpopOperationResult_Failure        = 2,
    XUserPlatformSpopOperationResult_Canceled       = 3
};

cpp_quote("#if 0")
struct APP_LOCAL_DEVICE_ID
{
    BYTE value[32];
};
cpp_quote("#endif")

struct XUserLocalId
{
    UINT64 value;
};

struct XUserDeviceAssociationChange
{
    APP_LOCAL_DEVICE_ID deviceId;
    XUserLocalId oldUser;
    XUserLocalId newUser;
};

struct XUserGetTokenAndSignatureData
{
    SIZE_T tokenSize;
    SIZE_T signatureSize;
    const CHAR *token;
    const CHAR *signature;
};

struct XUserGetTokenAndSignatureHttpHeader
{
    const CHAR *name;
    const CHAR *value;
};

struct XUserGetTokenAndSignatureUtf16Data
{
    SIZE_T tokenCount;
    SIZE_T signatureCount;
    const WCHAR *token;
    const WCHAR *signature;
};

struct XUserGetTokenAndSignatureUtf16HttpHeader
{
    const WCHAR *name;
    const WCHAR *value;
};

struct XUserPlatformRemoteConnectEventHandlers
{
    XUserPlatformRemoteConnectShowPromptEventHandler *show;
    XUserPlatformRemoteConnectClosePromptEventHandler *close;
    void *context;
};
